export { Home } from "./homePage/home";
export { Login } from "./authPage/login";
export { SignUp } from "./authPage/signup";
export { Explore } from "./explore/explore";
export { Playlist } from "./playlistPage/playlist";
export { WatchLater } from "./watchLaterPage/watchlater";
export { LikedVideo } from "./likedvideoPage/likedvideo";
export { SingleVideoPage } from "./singleVideoPage/singleVideoPage";
export { History } from "./historyPage/history";
